name: CI

on:
  push:
    branches: [main]
    paths:
      - "Sources/**"
      - "Package.swift"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "Sources/**"
      - "Package.swift"
      - ".github/workflows/ci.yml"

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Install libmagic
        run: brew install libmagic

      - name: Build
        run: swift build -v

      # - name: Run tests
      #   run: swift test -v

      - name: Analyze Swift Package
        run: swift package describe

  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict
